import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'README',
    {
      type: 'category',
      label: 'Как все это устроено',
      items: [{type: 'autogenerated', dirName: 'howto'}],
    },
    {
      type: 'category',
      label: 'По уровням власти',
      items: [{type: 'autogenerated', dirName: 'power'}],
    },
    {
      type: 'category',
      label: 'Государственные информационные системы',
      items: [{type: 'autogenerated', dirName: 'gis'}],
    },
    {
      type: 'category',
      label: 'Государственные и муниципальные организации',
      items: [{type: 'autogenerated', dirName: 'orgs'}],
    },
    {
      type: 'category',
      label: 'Открытые данные',
      items: [{type: 'autogenerated', dirName: 'opendata'}],
    },
    'faq',
    'glossary',
    {
      type: 'category',
      label: 'Приложения',
      items: [{type: 'autogenerated', dirName: 'addons'}],
    },
  ],
};

export default sidebars;
