import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'readme',
    {
      type: 'category',
      label: 'Каноническая структура базы знаний',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        },
        'glossary',
        {
          type: 'autogenerated',
          dirName: 'organizations',
        },
        {
          type: 'autogenerated',
          dirName: 'information-systems',
        },
        {
          type: 'autogenerated',
          dirName: 'budget-system',
        },
        {
          type: 'autogenerated',
          dirName: 'budget-classification',
        },
        {
          type: 'autogenerated',
          dirName: 'data-sources',
        },
        {
          type: 'autogenerated',
          dirName: 'howto',
        },
        {
          type: 'autogenerated',
          dirName: 'legal',
        },
        {
          type: 'autogenerated',
          dirName: 'reporting',
        },
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Legacy wiki (до миграции)',
      items: [{type: 'autogenerated', dirName: 'howto'}],
    },
    {
      type: 'category',
      label: 'Legacy: По уровням власти',
      items: [{type: 'autogenerated', dirName: 'power'}],
    },
    {
      type: 'category',
      label: 'Legacy: Государственные информационные системы',
      items: [{type: 'autogenerated', dirName: 'gis'}],
    },
    {
      type: 'category',
      label: 'Legacy: Государственные и муниципальные организации',
      items: [{type: 'autogenerated', dirName: 'orgs'}],
    },
    {
      type: 'category',
      label: 'Legacy: Открытые данные',
      items: [{type: 'autogenerated', dirName: 'opendata'}],
    },
    'faq',
    {
      type: 'category',
      label: 'Legacy: Приложения',
      items: [{type: 'autogenerated', dirName: 'addons'}],
    },
  ],
};

export default sidebars;
