import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Сайдбар книги «Открытые государственные финансы».
 * Структура отражает реально наполненные разделы wiki.
 */
const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'readme',
    {
      type: 'category',
      label: 'Введение',
      collapsed: false,
      link: {type: 'doc', id: 'intro/README'},
      items: [
        'intro/how-to-use',
        'intro/russian-budget-overview',
        'intro/key-laws',
      ],
    },
    'glossary',
    {
      type: 'category',
      label: 'С чего начать',
      link: {type: 'doc', id: 'howto/README'},
      items: [
        {
          type: 'category',
          label: 'Ключевые документы',
          link: {type: 'doc', id: 'howto/howtostart/README'},
          items: [
            'howto/howtostart/constitution',
            'howto/howtostart/budkodeks',
            'howto/howtostart/budgetlaw',
            'howto/howtostart/44fz',
            'howto/howtostart/223fz',
            'howto/howtostart/41fz',
            'howto/howtostart/8fz',
          ],
        },
        {
          type: 'category',
          label: 'Принципы открытости',
          link: {type: 'doc', id: 'howto/principles/README'},
          items: [
            {type: 'autogenerated', dirName: 'howto/principles'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Органы власти',
      link: {type: 'doc', id: 'power/README'},
      items: [
        {
          type: 'category',
          label: 'Федеральный уровень',
          link: {type: 'doc', id: 'power/fed/README'},
          items: [
            {
              type: 'category',
              label: 'Органы власти и регуляторы',
              link: {type: 'doc', id: 'power/fed/bodies/README'},
              items: [
                {type: 'autogenerated', dirName: 'power/fed/bodies'},
              ],
            },
          ],
        },
        'power/reg',
        'power/mun',
      ],
    },
    {
      type: 'category',
      label: 'Государственные информационные системы',
      link: {type: 'doc', id: 'gis/README'},
      items: [
        {
          type: 'category',
          label: 'Публичные системы',
          link: {type: 'doc', id: 'gis/public/README'},
          items: [
            {type: 'autogenerated', dirName: 'gis/public'},
          ],
        },
        {
          type: 'category',
          label: 'Закрытые системы',
          link: {type: 'doc', id: 'gis/closed/README'},
          items: [
            {type: 'autogenerated', dirName: 'gis/closed'},
          ],
        },
        'gis/gisaddonlist',
      ],
    },
    {
      type: 'category',
      label: 'Государственные и муниципальные организации',
      link: {type: 'doc', id: 'orgs/README'},
      items: [
        'orgs/publicbodies',
        'orgs/goventerprises',
        'orgs/others',
      ],
    },
    {
      type: 'category',
      label: 'Открытые данные',
      link: {type: 'doc', id: 'opendata/README'},
      items: [
        {
          type: 'category',
          label: 'Виды и типы данных',
          link: {type: 'doc', id: 'opendata/datatypes/README'},
          items: [
            {type: 'autogenerated', dirName: 'opendata/datatypes'},
          ],
        },
        'opendata/openprojects',
      ],
    },
    {
      type: 'category',
      label: 'Приложения',
      link: {type: 'doc', id: 'addons/README'},
      items: [
        'addons/fedpower',
        'addons/regpower',
      ],
    },
    'faq',
  ],
};

export default sidebars;
